{
    'name': "Advanced Property Management",
    'version': '18.0.1.0.0',
    'category': 'Industries',
    'summary': """Manage your properties by selling, renting and bidding""",
    'description': """The module makes it simple for you to manage your properties""",
    'author': "BAY Emporium Ltd.",
    'company': 'BAY Emporium Ltd.',
    'maintainer': 'BAY Emporium Ltd.',
    'depends': ['mail', 'sale_management', 'website', 'base_geolocalize'],
    'data': [
        'security/user_groups.xml',
        'security/property_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/advanced_property_management_data.xml',
        'data/ir_cron_data.xml',
        'views/property_property_views.xml',
        'views/property_facility_views.xml',
        'views/property_tag_views.xml',
        'views/property_search_pannel_views.xml',
        'views/property_templates.xml',
        'views/property_commision_views.xml',
        'views/property_sale_views.xml',
        'views/property_rental_views.xml',
        'views/res_partner_views.xml',
        'views/rental_bill_views.xml',
        'views/property_auction_views.xml',
        'views/property_owner_views.xml',
        'views/land_info_views.xml',
        'views/land_configure_views.xml',
        'views/mouza_name_views.xml',
        'reports/property_sale_report.xml',
        'views/property_room_view.xml',
        'views/case_pending_view.xml',
        'views/property_room_view.xml',
        'views/building_info_view.xml',
        'views/land_tax_view.xml',
        'views/land_mutation_info_view.xml',
        'views/building_structure_plan_view.xml',
        'reports/property_report.xml',
        'wizards/property_sale_report_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'advanced_property_management/static/src/js/property_website.js',
            'advanced_property_management/static/src/js/property_item.js',
        ],
    },
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
